Added accuracy property
ebidel/geo-location pull request #34
Opened 2018-02-22 23:15 UTC by benquan

I have a added the accuracy property to be pulled to the project.

2018-02-23 23:12 UTC, ebidel requested changes

2018-02-23 23:12 UTC, ebidel commented on geo-location.html
> +    _onPosition: function (pos) {
keep as is

2018-02-23 23:12 UTC, ebidel commented on geo-location.html
> +      this._setAccuracy(pos.coords.accuracy)
end with `;`

2018-02-23 23:12 UTC, ebidel commented on geo-location.html
> +    _onError: function (err) {
keep as is

2018-02-23 23:12 UTC, ebidel commented on geo-location.html
> +</script>
newline

2018-02-24 20:33 UTC, benquan commented
Changes ready

2018-02-25 20:09 UTC, ebidel requested changes

2018-02-25 20:09 UTC, ebidel commented on .vscode/settings.json
> +{
let's remove this file.

2018-02-26 07:51 UTC, FluorescentHallucinogen commented
@ebidel @benquan Do we need a separate property for this, while we can access it via the `position` object property?

```html
<geo-location
    watch-pos
    high-accuracy
    position="{{position}}">
</geo-location>

<p>Accuracy: [[position.coords.accuracy]]</p>
```

If yes, I can create a pull request that adds separate properties for all `position` object properties such as accuracy, altitude, altitude accuracy, heading, speed, timestamp. :wink:

2018-02-27 05:11 UTC, ebidel commented
@FluorescentHallucinogen that's a good point. I exposed lat/long b/c those are the most common but you can get accuracy through `position`. 

I don't think we need properties for all the sub properties :)

2018-02-27 07:18 UTC, FluorescentHallucinogen commented
@ebidel On the other hand, the separate properties are more easy to use. As you can see, not all users know / understand that accuracy, altitude, altitude accuracy, heading, speed, timestamp, etc. are hidden behind the `position` object.

2018-02-27 16:52 UTC, ebidel commented
Every property does come at a cost (observerss, listeners, etc.) I think examples and docs help with showing what's possible.

2018-03-02 10:45 UTC, FluorescentHallucinogen commented
@ebidel Could this pull request be closed?

2018-03-02 17:17 UTC, ebidel commented
Closing since `position` already gives you this info. Appreciate the PR @benquan!

2018-03-02 17:17 UTC, closed without merging